management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group
spring:
  ai:
    dashscope:
      api-key: ${ai_api_key}
  application:
    name: chaos
  datasource:
    vector:
      jdbc-url: jdbc:postgresql://localhost/vector_store
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
  mandatory-file-encoding: UTF-8

#    mcp:
#      client:
#        name: my-mcp-client
#        version: 1.0.0
#        request-timeout: 30s
#        type: ASYNC
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8081

  # 调试日志
  logging:
    level:
      io:
        modelcontextprotocol:
          client: DEBUG
          spec: DEBUG
      io.camunda.zeebe:
        client: DEBUG
      io.grpc:
        netty: DEBUG
  main:
    allow-bean-definition-overriding: true

camunda:
  bpm:
    client:
      base-url: http://localhost:8080
    zeebe:
      broker:
        gateway-address: localhost:26500